[server]
address = "127.0.0.1"
port = 8501
headless = true
runOnSave = false
allowRunOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "127.0.0.1"
serverPort = 8501

[theme]
base = "light"
primaryColor = "#00629B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "error"

[client]
showErrorDetails = false
toolbarMode = "minimal"
