[server]
address = "127.0.0.1"
port = 8503
headless = false
runOnSave = true
allowRunOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "127.0.0.1"
serverPort = 8503

[theme]
base = "light"
primaryColor = "#DC2626"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#374151"

[logger]
level = "error"

[client]
showErrorDetails = false
toolbarMode = "minimal"
